# Generated by Django 4.2.8 on 2025-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_service_options_remove_review_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('MANICURE', 'Manicure'), ('PEDICURE', 'Pedicure'), ('MORE', 'More')], default='MANICURE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='main_servic_categor_60109a_idx'),
        ),
    ]
