# Generated by Django 4.2.8 on 2025-11-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_schedules', to='main.branch'),
        ),
    ]
