# Generated by Django 4.2.8 on 2025-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='minutes'),
        ),
    ]
