# Generated by Django 4.2.8 on 2025-11-13 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service_duration'),
    ]

    operations = [
        # ----- các field mới của Review -----
        migrations.AddField(
            model_name='review',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='product_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='service_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reviews/videos/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('CONFIRMED', 'Confirmed'),
                    ('IN_PROGRESS', 'In progress'),
                    ('DONE', 'Done'),
                    ('CANCELED', 'Canceled'),
                    ('ARRIVED', 'Đã đến'),
                    ('ONGOING', 'Đang thực hiện'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/photos/'),
        ),

        # ----- ContactMessage: chỉ cập nhật STATE, KHÔNG đụng DB -----
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # không chạy SQL tạo bảng (bảng đã tồn tại)
            state_operations=[
                migrations.CreateModel(
                    name='ContactMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('full_name', models.CharField(max_length=120)),
                        ('email', models.EmailField(max_length=254)),
                        ('phone', models.CharField(max_length=20)),
                        ('content', models.TextField()),
                        ('branch_name', models.CharField(blank=True, max_length=120)),
                        ('status', models.CharField(
                            choices=[
                                ('new', 'New'),
                                ('in_progress', 'In progress'),
                                ('resolved', 'Resolved'),
                            ],
                            default='new',
                            max_length=20,
                        )),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('source', models.CharField(default='web', max_length=20)),
                        ('assigned_to', models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name='assigned_contacts',
                            to=settings.AUTH_USER_MODEL,
                        )),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
    ]
