# Generated by Django 4.2.8 on 2025-11-13 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_review_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='loyalty_awarded',
            field=models.BooleanField(default=False, help_text='Đã cộng điểm loyalty cho lịch này chưa?'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EARN', 'Earn'), ('USE', 'Use'), ('ADJUST', 'Adjust')], default='EARN', max_length=20)),
                ('points', models.IntegerField(help_text='>0 là cộng, <0 là trừ')),
                ('balance_after', models.IntegerField(default=0, help_text='Số điểm còn lại sau giao dịch')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='main.appointment')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
