"""
Django settings for glamup_nails project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cb)i^tqtu*3hk$_ak3%mlw%2@va#asidk(^*#*u+ot(08@qo+@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'glamup_nails.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': [BASE_DIR / 'templates'],  # <-- THÊM DÒNG NÀY
        'OPTIONS': {
            'libraries': {
                'dict_extras': 'main.templatetags.dict_extras',
            },
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'glamup_nails.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'main.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'main' / 'static']   # nạp CSS/JS/ảnh trong app
STATIC_ROOT = BASE_DIR / 'staticfiles'              # phục vụ collectstatic khi deploy

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'main:login'

LOGIN_REDIRECT_URL = 'main:customer_account'
LOGOUT_REDIRECT_URL = 'main:login'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_TZ = True

# settings.py (thêm hoặc kiểm tra)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" #Cách gửi email mà hệ thống sử dụng là SMTP, kết nối với gmail để gửi mail
EMAIL_HOST = "smtp.gmail.com" #Đây là địa chỉ máy chủ mail (SMTP server), smtp.gmail.com là server gửi mail của Google.
EMAIL_PORT = 587 #Đây là cổng kết nối SMTP
EMAIL_USE_TLS = True #Mã hóa dữ liệu khi gửi mail,Tránh bị nghe lén, đánh cắp thông tin,Nếu không bật TLS,Gmail từ chối kết nối
EMAIL_HOST_USER = "tothiennha.ec@gmail.com"
EMAIL_HOST_PASSWORD = "ocedmxogauwcztfk"
DEFAULT_FROM_EMAIL = "Glamup Nails <tothiennha.ec@gmail.com>"


